### ISSUE TITLE
NH010 - Data registration within Data Orchestration Service

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-docs#10]
# Problem:
Initial Data Orchestration Service has to be implemented with the first endpoint:
`POST` /register
with payload:
```javascript
{
  "key": [
    "string"
  ],
  "url": "string"
}
```

# Solution
Base your implementation on existing `nhood-data-url-svc`.
Endpoint will vaidate the request and call an empty business service.

# Acceptance Criteria:
- All common service features are available
- Endpoint is exposed
- Endpoint input is validated

**Comment by 1milosz2** [comment]
Solution has been created within https://github.com/nhood-org/nhood-data-orch-svc
