### ISSUE TITLE
NH048 - Enhance testing of nhood-api-gateway

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-docs#48]
# Problem

There are not e2e tests of nhood-api-gateway.

# Solution

Implement simple integration tests with rest assured or similar library that check if all expected endpoints are exposed.
Base all tests on a test application-test.yml configuration.

# Acceptance criteria:

- Tests are implemented
- Tests passes

**Comment by krzysztofreczek** [comment]
@1milosz2, does this story look like a one for you? ;)

**Comment by 1milosz2** [comment]
sure, looks intriguing:) I'll take care of this in the reasonable near future:)

**Comment by krzysztofreczek** [comment]
Will not be implemented yet
