### ISSUE TITLE
NH049 - Enhance root endpoint of nhood-api-gateway

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-docs#49]
# Problem

We want to have a whole list of `nhood-api-gateway` endpoints printed on the default `GET` \ root endpoint.

# Solution

Enhance string response returned from RootController with a list of endpoints configured within `nhood-api-gateway` application.yml configuration. Try to use internal gateway components to resolve that list dynamically.

# Acceptance criteria

- Solution is implemented
- Solution is covered with unit tests

**Comment by krzysztofreczek** [comment]
@1milosz2, yet another one for you:)

**Comment by 1milosz2** [comment]
man, that escalated quickly!

**Comment by krzysztofreczek** [comment]
Will not be implemented yet
