### ISSUE TITLE
NH008 - Select and apply license

### ISSUE THREAD

**Issue by krzysztofreczek** [nhood-org/nhood-docs#8]
License for the open-source project has to be selected and applied in accordance with best practices and license requirements. There are few to recognize: MIT, Apache 2.0, BSD, GPL
Please check:
- license scope
- license requirements
- find good open source project example

**Comment by jarekjaro** [comment]
MIT and Apache 2.0 are both good :) is there any special features we look for?

**Comment by krzysztofreczek** [comment]
I guess we have to select one Of those two. All we need is to understand the difference and select one. What is albo important is each of those licenses has defined requirents for project to be aligned with (file headers, license docs, etc). Those have to be applied to our project.

**Comment by krzysztofreczek** [comment]
This [article](https://medium.freecodecamp.org/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94) has potential.

**Comment by 1milosz2** [comment]
I believe that both [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) and [MIT](https://choosealicense.com/licenses/mit/) are described pretty clearly, on linked pages. It also describes steps to follow when applying each of those.

The biggest difference would be that, while using the Apache 2.0, changes made to the code have to be documented. Moreover, it provides an express grant of patent rights and limits trademark use.

**Comment by krzysztofreczek** [comment]
I would go with MIT then, wich seems to be a bit simpler and easier to apply. @1milosz2 are you going to apply this license to nhood-data-url-svc so we can see how it looks like? Find a good project with MIT and be inspired:D

**Comment by krzysztofreczek** [comment]
I like this simple answer: https://www.quora.com/Whats-the-difference-between-Apache-v2-0-and-MIT-license-What-are-the-major-consequences-of-using-Apache-software-over-MIT

**Comment by krzysztofreczek** [comment]
Apache 2.0 is clearly product-oriented. They want to be sure no one creates another Apache Spark or Apache Camel. We do not need that for nhood.

**Comment by 1milosz2** [comment]
Sure, I'll take care of this:)

**Comment by krzysztofreczek** [comment]
One more thing, please check what does this license mean for us in terms of our dependencies. Those have different licenses. Do we need to document/disclose a list of our dependencies and its licenses? What are the limitations here.  I am sure we are not able to use GPL for example, as this is so-called "virus" license.

**Comment by 1milosz2** [comment]
I opened pull request for MIT license application. Referring to your latest comment, MIT is one of the most permissive licences, so we have to check if we're not using any of the less permissive ones. The toll to do so might be: [licenscan-maven-plugin](https://github.com/carlomorelli/licensescan-maven-plugin) or any of the mentioned in the [article](https://carlomorelli.github.io/2018/04/01/Audit-licenses-in-your-Java-dependencies.html).

**Comment by krzysztofreczek** [comment]
Cool! Let's create a separate issue to add that plugin in the future. @1milosz2, could you please create such?
